export { PostViewModal } from '@/widgets/postViewModal/UI/PostView/PostViewModal'
export { PostViewSmall } from '@/widgets/postViewModal/UI/PostView/PostViewSmall'
export { ModalContentUI } from './UI/ModalContent/ModalContentUI'
export { ModalContentWithEditUI } from './UI/ModalContent/ModalContentWithEditUI'
export { PostViewModalSSR } from '@/widgets/postViewModal/UI/PostView/PostViewModalSSR'
